### ISSUE TITLE
IP Address Rule

### ISSUE THREAD

**Issue by oarmstrong** [dustinrue/ControlPlane#125]
Is it possible to include wild cards for the IP address rule?  E.g. 192.168.1._?  When I connect to college I have to use DHCP and it's so far impossible to tell the exact IP I will get, however I know that it's in the 172.16._.\* range.  Can ControlPlane introduce the ability to use wildcard asterisks in the IP address field?

**Comment by ldong** [comment]
@dustinrue Thank you for the tip.
BTW, I used [Online IP Subnet Calculator](http://www.subnet-calculator.com/) to calculate the IP range.
