### ISSUE TITLE
Can "Mount" action mount a local file?

### ISSUE THREAD

**Issue by ghost** [dustinrue/ControlPlane#136]
I'd like the mount action to mount a local sparsebundle/dmg file, but the help only shows examples to smb:// and afp://. Can I do something like:
'file://Users/me/Personal.sparsebundle' ?

**Comment by frerich** [comment]
👍 for this question (and the answer) - I was wondering the exact same thing, seeing how my attempts to 'mount' a `.sparsebundle` all failed.
