### ISSUE TITLE
Screensaver password delay action

### ISSUE THREAD

**Issue by nbriders** [dustinrue/ControlPlane#267]
hello
not sure if this counts as a feature request, but adding (re-adding, really) and option to change the time before a screensaver password is reuqested (given that disabling it with FV2 enabled is impossible) would be great!
thanks, Michael

**Comment by eric2** [comment]
Can I re-open this? Or better to make a new feature request? I don't use FV at all. But I'd prefer changing the password delay time as I move between contexts, to enabling and disabling password protection altogether.  I believe the relevant value is askForPasswordDelay.  Also, in case it helps, I believe I read somewhere that behavior may be different if the native System Preferences app is open at the time a programatic change is made to askForPasswordDelay (so maybe better to test with that app closed.)  Thanks!
