### ISSUE TITLE
Multiple active contexts with same icon colour should be honored

### ISSUE THREAD

**Issue by catchamonkey** [dustinrue/ControlPlane#369]
I have multiple contexts active.

Default context is my Home
Another context is for my office locaiton
Another context is for when i'm wired (network) in my office

Both office contexts have the same icon colour, but when they are both active (i'm in the office and wired to the network), the icon stays on the default Home colour.

If multiple contexts are active, and they have the same colour, it should set to that colour still.

**Comment by VladimirTechMan** [comment]
I have pushed a fix that will enable that in the next public release of CP.

**Comment by catchamonkey** [comment]
Excellent, thanks!
