### ISSUE TITLE
Menu Bar Icon Colour Not Working (1.5.4)

### ISSUE THREAD

**Issue by cblecker** [dustinrue/ControlPlane#373]
Since the upgrade to 1.5.4, the Menu Bar Icon colour doesn't seem to work anymore. Even when I select the "preview" check box, the icon stays black the entire time.

**Comment by ajmaggs** [comment]
Still broken in 1.5.6 release. Menu bar icon will not change colour when context changes. I have reverted back to 1.5.3 which works perfectly (but is obviously missing features/bugfixes that are in 1.5.4 and 1.56). Is there any plan to get this issue fixed?

**Comment by VladimirTechMan** [comment]
Hi @ajmaggs, I should be able to address this issue in over the next week. Both Dustin and I were tied up with our main job activities in the recent time, thus could not address this issue as quick as CP users might have expected. Apologies for the delay.

Vladimir

**Comment by munum** [comment]
Look forward to it!

**Comment by VladimirTechMan** [comment]
It should work well in the next public release of CP.
