### ISSUE TITLE
Default browser not used when opening HTML file

### ISSUE THREAD

**Issue by deanmorin** [dustinrue/ControlPlane#379]
If you try to open an HTML file on disk, you get the error message:

The document "x.html" could not be opened. ControlPlane cannot open files in the "HTML text" format.

![image](https://cloud.githubusercontent.com/assets/416052/5074771/7a6f84d2-6e42-11e4-9423-a08b1e1132de.png)

**Comment by dustinrue** [comment]
Fixed in next release
