### ISSUE TITLE
Mounting smb volume uses only first part of the share path

### ISSUE THREAD

**Issue by kalprestito** [dustinrue/ControlPlane#384]
I'd like to use ControlPlane to connect to my university's network share when in campus or when connected through VPN. The full path to the share is something like `smb://nas.upv.es/students/shares/myusername`. However, upon activating the `University` context, the Finder tries to mount `smb://nas.upv.es/students`. It seems like ControlPlane only takes the first past of the share path.

**Comment by dustinrue** [comment]
With any luck it'll be released today
