### ISSUE TITLE
Change computer host name and address

### ISSUE THREAD

**Issue by kalprestito** [dustinrue/ControlPlane#385]
My university's network always messes up with stock computer names (like `John's MacBook Pro` going to `John's MacBook Pro 3` because there are two others with that name). In that context, it doesn't matter, but when I get back home I usually access my laptop through Bonjour, so I have to change my laptop's name manually. Could there be an action for this? Thanks

**Comment by dustinrue** [comment]
Not sure if this is an action I want to add or not but you can create a script that does it for you - http://osxdaily.com/2010/09/06/change-your-mac-hostname-via-terminal/. You'd also need to configure sudo to allow you to run the scutil command without a password though.
