### ISSUE TITLE
ControlPlane 1.5.4 crashes on Yosemite when computer goes standby

### ISSUE THREAD

**Issue by aapit** [dustinrue/ControlPlane#386]
ControlPlane crashes on me a couple of times a day. Whenever I put my MacBook on standby, it crashes without a warning. When I start it up again, it presents me with a standard crash dialogue, offering me to send a report.

**Comment by NitroG42** [comment]
Hi everybody, just to let you know that I git cloned the project and will fix this issue. I probably found the cause but will wait tomorrow or the day after to be sure. Then I'll create a pull request to fix it as quickly as possible.

**Comment by dustinrue** [comment]
Looking forward to the request, thanks.

Dustin

**Comment by NitroG42** [comment]
Here's my pull request : https://github.com/dustinrue/ControlPlane/pull/396
The fix is pretty stupid but I can say I didn't have any crash from 2 days (so I can clearly say it fixed the problem because just going from work to my home made it crashes).

**Comment by aapit** [comment]
Kudos, NitroG42 and Dustin! Thanks a lot for that.
This seems to fix it for me, too.
