### ISSUE TITLE
Wrong label in "Attached Power Adapter" rule pane

### ISSUE THREAD

**Issue by rinopo** [dustinrue/ControlPlane#392]
Hi,

In the "Attached Power Adapter" setting pane it says "The following application is active".
It should say something like "The following power adapter is attached".

![dialogue](https://cloud.githubusercontent.com/assets/45791/6181797/ef3eed7e-b37b-11e4-97af-b3b8bdbc5451.png)

**Comment by VladimirTechMan** [comment]
Thanks for reporting! I have pushed a fix for that. You will see the appropriate suggestion text in the next public release of CP.

**Comment by rinopo** [comment]
Thank you for letting me know!
Looking forward to the next release.
