### ISSUE TITLE
Delay time for network location change not working

### ISSUE THREAD

**Issue by rosch100** [dustinrue/ControlPlane#393]
When I change my location and trigger a network location change, the change is initiated immediately independent of the configured delay time.
The delay time (e.g. 5 or 10s) is not honored.
Thus, the network location change fails in my case.

**Comment by clhynfield** [comment]
I have the same issue, and it's interfering with an AppleScript I'm trying to use to enable/suspend my VPN connection. I've tried upping the delay to as much as 30 seconds, as well as removing the Network Location action and re-adding it, but it always triggers immediately on context switch.

**Comment by clhynfield** [comment]
Works perfectly now, @dustinrue—thank you! :+1:
