### ISSUE TITLE
Ampersand being incorrectly escaped

### ISSUE THREAD

**Issue by cblecker** [dustinrue/ControlPlane#404]
When ControlPlane is set as the default browser, and a link is passed to it, ControlPlane is incorrectly trying to escape the ampersand symbol in the query string part of the URL as %26 . This breaks any URL that has multiple variables in the query string as the ampersand is used as the separator.

**Comment by dustinrue** [comment]
Please try this build - http://www.controlplaneapp.com/download/ci

**Comment by cblecker** [comment]
That fixed it! Cheers for the fast response.

**Comment by dustinrue** [comment]
I'll include it in the next public release, that build will not "see" it so be sure to either watch for the release on twitter or keep running the public release.
