### ISSUE TITLE
Feature Request: Adjust timeout for requiring password after screensaver

### ISSUE THREAD

**Issue by LucaTNT** [dustinrue/ControlPlane#408]
Hi,
I've been using CP for a while now, and I really enjoy it.

One feature I'd like to see added is the ability to set a custom timeout for requiring password after screensaver has started. I've tried with `defaults write com.apple.screensaver askForPasswordDelay -int DELAY_IN_SECONDS` but it is extremely unreliable.

The main purpose of this is to have a generous timeout while at home (say 15 minutes), while requiring a password immediately while I'm on the go.

Would that be possible?

Thanks,
Luca

**Comment by dustinrue** [comment]
ControlPlane used to do this, but it can't anymore due to restrictions (and rightly so honestly) put into OS X in the past few versions.
