### ISSUE TITLE
Interface with 3rd party apps

### ISSUE THREAD

**Issue by perfaram** [dustinrue/ControlPlane#415]
###### In the same vein : #337 "Implement plugin support for actions"
Hi ! 
I'm currently writing an app similar to Nocturne/F.Lux, that I plan to release as closed-source. I really like ControlPlane, and I'd like to interface my app with it - so that ControlPlane could fire my app at determined times & places, or when my external monitor gets connected. Or even tell it to revert to standard color profile when VLC is started, etc...
What would be the best way ?

Thanks for the nice job on ControlPlane !

**Comment by perfaram** [comment]
Do you think AppleScript would be the way ?

**Comment by dustinrue** [comment]
If your app supports AppleScript then ControlPlane users could interact with it.
