### ISSUE TITLE
Screensaver enable password not working

### ISSUE THREAD

**Issue by tomcat335** [dustinrue/ControlPlane#421]
The function to enable the screensaver password when arriving at a location doesn't seem to be working. I'm on MacOS 10.11 and it seems to have started after I upgraded.

**Comment by dustinrue** [comment]
Check for updates, ensure you are using the latest release

**Comment by tomcat335** [comment]
Running version 1.6.1.

**Comment by ColdDevil** [comment]
Same for me with 10.11 and 1.6.1. Also forcing a context does not help.. Although the message is shown that the screensaver password got (de)activated it does not work.

**Comment by briemens** [comment]
I can even add that the `Require Password` checkbox is even checked, but OS X 10.11 doesn't pick it up until you manually disable/enable it.

**Comment by gfarrell** [comment]
(1.6.1)

I've found that ControlPlane says it's enabling/disabling the screensaver password, and the box is checked/unchecked as appropriate in system preferences, but that OSX does not take any notice of this, unless I do it manually.

The apple script from SE worked for me too (reposted here for posterity):

    sudo osascript -e 'tell application "System Events" to set require password to wake of security preferences to false'

**Comment by timothykang** [comment]
I don't have the ability to test it, but I am pretty sure the action no longer works even for <10.11.

I believe this is related to fb44351, in that the deleted line was there to cause the setting to be "reloaded" (see https://web.archive.org/web/20141112135724/http://hintsforums.macworld.com/showthread.php?t=49718#13).

At minimum the delete line probably needs to be restored and a check for <10.11 be made, but unfortunately that would not fix this action for 10.11.

**Comment by repertor** [comment]
Still does not work on 10.11.1

**Comment by DHKaplan** [comment]
Just discovered this support site. I'm also on 10.11.1, running CP 1.6.1 and can manually set the password requirement and have it work, but if CP tries, IT thinks it's doing it but it is not activating it.

**Comment by p3ppo** [comment]
Can confirm this, I have the same problem. I'm on 10.11.1, running ControlPlane 1.6.1. The checkbox is checked/unchecked in System Preferences, but OS X doesn't care, unless you do it manually.

**Comment by herbhoppe** [comment]
I have the same problem... really looking forward for a fix

**Comment by kingmatusevich** [comment]
have this problem too, 10.11

**Comment by dreammaker** [comment]
@timothykang, 1.6.1 works on OS X 10.10.  I was using the enable/disable password until just recently when I upgraded to El Capitan, and it stopped working.

**Comment by Jactaen** [comment]
Same problem as the rest, won't work in El Capitan

**Comment by lhaeger** [comment]
I was hoping 1.6.2 solves this, but unfortunately is doesn't...

**Comment by ColdDevil** [comment]
Version 1.6.2 changes the checkbox in OS X preferences but it still has no effect unfortunately.

**Comment by Pulloverman** [comment]
Same with Version 1.6.2, unfortunately still does not work under 10.11.3.

**Comment by richellis** [comment]
Workaround: put the AppleScript referenced by @gfarrell in a shell script and then have ControlPlane fire the script using a System Action.

I didn't include the `sudo` in the script and it works fine.

```
#!/bin/sh
osascript -e 'tell application "System Events" to set require password to wake of security preferences to false'
```

Make a corresponding script with the last value set to `true` to have a script that re-enables the screensaver password:

```
#!/bin/sh
osascript -e 'tell application "System Events" to set require password to wake of security preferences to true'
```

![snip20160209_6](https://cloud.githubusercontent.com/assets/13336831/12935009/e5369174-cf4f-11e5-9981-6994cf3eba72.png)

**Comment by tomcat335** [comment]
Thanks for the tip! Adding the shell scripts worked for me. Nice workaround.

**Comment by p3ppo** [comment]
Can confirm, same with Version 1.6.2. Still does not work under 10.11.3.
I'm using the shell script workaround. Thanks @gfarrell and @richellis 👍

**Comment by ColdDevil** [comment]
Thanks! Great workaround! :smile: :+1:

**Comment by dustinrue** [comment]
I incorporated the apple script into ControlPlane and it is used for 10.11.

**Comment by garee76** [comment]
Still not working for me! Control Plane 1.6.4 and OSX 10.11.3

**Comment by richellis** [comment]
Me neither, I went back to my workaround shell scripts. Those still work great. 






On Tue, Mar 8, 2016 at 1:00 PM -0800, "garee76" <notifications@github.com> wrote:












Still not working for me! Control Plane 1.6.4 and OSX 10.11.3

**Comment by dustinrue** [comment]
I'm testing this and it's working perfectly on my system.

**Comment by tharwan** [comment]
stopped working for me again with 10.11.6.

**Comment by tomcat335** [comment]
Same with me on 10.12, and the script workaround doesn't seem to be working properly either.

**Comment by fingolfin** [comment]
Also doesn't work for me on 10.11.6 with Control Plane 1.6.5

**Comment by dreammaker** [comment]
The script workaround used to work for me on 10.11, but even the script stopped working for me after upgrading to 10.12 Sierra.  I'm using Control Plane 1.6.5.

**Comment by dustinrue** [comment]
I'll be honest and say that I haven't actually looked into this, but if history has taught me anything about this feature, Apple has slowly improved the security of the password lock with each release. It's highly likely this cannot be worked around and the feature (in ControlPlane) will need to go away.

**Comment by dreammaker** [comment]
That's sad to hear.  _This one feature_ is the reason I sought out and found ControlPlane.  I'd be happy to help any way I can to keep this feature, but I'm not familiar with the relevant APIs and wouldn't really know where to begin.

**Comment by tharwan** [comment]
I could imagine if we all file a bug at Apple we might have a chance of either getting it fixed or a definite answer. I mean it is a valid Apple Script to set/unset the checkmark, but then nothing happens, which is clearly a bug.
