### ISSUE TITLE
Possible problem with auto-update for 1.6.1

### ISSUE THREAD

**Issue by pccowboy** [dustinrue/ControlPlane#422]
Running 10.10.5, and a controlplane 1.5.8.  Got an 'Update and relaunch' message.  it appears it did not relaunch cleanly.  My machine started beachballing for minutes at a time.  I went ahead and stopped CP, and manually installed 1.6.1.  After reinstalling 1.6.1 manually, it seems to be operating normally.  Are there any logs I can look at, to get some idea of what happened?

**Comment by dustinrue** [comment]
Auto updating is handled by a separate library, there aren’t any logs related to it that I’m aware of. Sometimes this happens with apps that use the library, not sure what causes it.

**Comment by pccowboy** [comment]
OK.  Thought if there was data I could send I would.  Reinstalling from scratch seems to have taken care of most of my issues.
 Thanks!
