### ISSUE TITLE
Pause detection while in standby?

### ISSUE THREAD

**Issue by Argon-** [dustinrue/ControlPlane#426]
From time to time I come back to my MBP (standby by closing the lid, 10.10.5) and upon wake it shows >30 new notifications (switch smoothing is enabled) by ControlPlane. I'm not entirely sure why this happens.
I only have 3 contexts and they switch only based on WiFi SSID but since I have AppNap disabled I assumed no application is running (and WiFi is not scanning) while my MBP is "sleeping".

Is this ControlPlane still reacting to some events while "sleeping"? In this case, what about a possibility to cease performing any actions during sleep?

**Comment by dustinrue** [comment]
Sounds like you have your laptop plugged into power while it is sleeping and it is waking periodically to do some tasks. This is called PowerNap and will cause the issues you are seeing. I'm not currently aware of a way for ControlPlane to know if the system is waking because of Power Nap or because you opened the lid but I can look into it. You can disable notifications if you prefer but there is currently no way to have ControlPlane stop behaving this way.

**Comment by Argon-** [comment]
No it was not plugged in. I also disabled PowerNap for both battery and AC powered -- that's why I'm not really sure what's going on myself. I have wake on WiFi access disabled too.
Still, looking at the logs the MBP is waking up frequently due to WiFi scans. According to google this is a known problem of OSX I was not aware of (therefore assumed it might have something to do with ControlPlane). I'm sorry!

**Comment by sn0wyfall** [comment]
This happens to me too. I guess disabling notifications is the best way to go about over here.

**Comment by dustinrue** [comment]
I haven't had this issue but I also have notifications disabled. I've enabled notifications and I'll watch for it.

**Comment by Argon-** [comment]
In the meantime, through unrelated issues, I learned that MBPs waking because of some Wifi events while they should sleep (even without AppNapp) is a common occurrence for many OSX versions now. For some users this happens so excessively that their batteries are drained by a substantial amount overnight. This bug exists for multiple OSX versions as well (fortunately, I'm not effected but I see occasional wake-ups because of Wifi in my logs as well).
