### ISSUE TITLE
Disable Bluetooth not Working

### ISSUE THREAD

**Issue by SirWilli** [dustinrue/ControlPlane#429]
hey,
I did set a action to disable bluetooth on leave but nothing is happening.
In rules the tick does appear and disappear correctly so the event seems to work correctly.

Version 1.6.1 on El Capitan

**Comment by dustinrue** [comment]
The rules match but are they confident enough to switch contexts?

**Comment by SirWilli** [comment]
Hm, I can't follow. What do you mean?

**Comment by dustinrue** [comment]
Rules are what trigger the context changes but if you've set the confidence of the rules too low then a context change won't happen.

Confidence required to change below
<img width="525" alt="screenshot 2015-10-30 10 38 44" src="https://cloud.githubusercontent.com/assets/573953/10850223/6ff1708a-7ef2-11e5-840a-66818649886a.png">

Confidence of a rule
<img width="606" alt="screenshot 2015-10-30 10 39 47" src="https://cloud.githubusercontent.com/assets/573953/10850247/8c9eab94-7ef2-11e5-8413-8dc9eab28238.png">

If the confidence of a rule isn't greater than the confidence required nothing will happen.

**Comment by SirWilli** [comment]
Ah, my required confidence is on 75% and the rule on 70%. The context switches between 68% and 90%. Does it inherit something from the context above?
Like
home: 70%
     room1: 68%

**Comment by dustinrue** [comment]
It can depending on how you have setup sub contexts and how many.

**Comment by SirWilli** [comment]
I got it to work now but is there no way to have multiple contexts active?
I want to have to login password disabled in a specific wifi and toggle bluetooth but the issue is that it will toggle bluetooth too when I disable/enable wifi.

**Comment by dustinrue** [comment]
Under advanced select the option for multiple active contexts. Works great.

**Comment by SirWilli** [comment]
Oh thanks, Completely missed this tick box. Works now great :)
