### ISSUE TITLE
Feature Request: Add Pulse Secure to Evidence Sources

### ISSUE THREAD

**Issue by kaspermalfroid** [dustinrue/ControlPlane#430]
At my current job, we have to use the [Pulse Secure](https://www.pulsesecure.net) software (used to be called Juniper Junos Pulse) to connect to the company VPN when working from home.
I would like to be able to switch context in ControlPlane based on when I connect to a particular VPN server.
<img width="376" alt="screen shot 2015-11-02 at 10 03 43" src="https://cloud.githubusercontent.com/assets/3715399/10877925/c43ad096-814a-11e5-8e81-15804e98ee44.png">

**Comment by dustinrue** [comment]
You'll want to try getting this to work using the Shell Script evidence source. I try to implement evidence sources using whatever is available in OS X.
