### ISSUE TITLE
Modifying rule parameter doesn't change 'Description' in the table

### ISSUE THREAD

**Issue by rshev** [dustinrue/ControlPlane#434]
Pretty much that. Steps to reproduce:
1. Open Preferences on Rules tab.
2. Choose a rule.
3. Click gear to modify.
4. Change the parameter field.
5. Click 'OK'.
6. Description field in the table doesn't reflect the modification (unless it's just arbitrary description and filled only when adding?)

Please elaborate, maybe I'm just implying something that shouldn't work as I think :)

**Comment by dustinrue** [comment]
It is initialized on add but not again after that. Not something I plan on changing.
