### ISSUE TITLE
Website says latest is for Snow Leopard

### ISSUE THREAD

**Issue by mrjcleaver** [dustinrue/ControlPlane#435]
Per http://www.controlplaneapp.com I see: 
![ruedu controlplane 2015-12-14 10-09-35](https://cloud.githubusercontent.com/assets/59202/11784566/feea6e56-a24a-11e5-8bb9-a88bf9052f7d.png)

i.e. under DOWNLOADS
Latest version for Snow Leopard:
ControlPlane 1.2.3

Can I assume that it's much more modern than this?

**Comment by dustinrue** [comment]
The website also says the latest version for Lion+ is 1.6.1.

**Comment by mrjcleaver** [comment]
Oh, I now see. Well, that + is tiny. 

Perhaps list the Lion+ version first?

Thanks,
   Martin.
