### ISSUE TITLE
Shell Script execution

### ISSUE THREAD

**Issue by patowod** [dustinrue/ControlPlane#438]
Hi everyone, I've been trying to run my shell script through an action and tried everything I can find. Somehow it's not executed, though. Here is what I got: 

---

#!/bin/sh
mackup backup -f
exit 0

---

Running it within the terminal works fine and as expected. ControlPlane itself says: 
23:57:21.648 __56-[ShellScriptAction launchTaskWithLaunchPath:arguments:]_block_invoke
	Finished executing '/Users/Username/Dropbox/scripts/run-mackup.sh'

Any ideas are appreciated. Thanks in advance…

**Comment by dustinrue** [comment]
Try specifying the full path to mackup

**Comment by patowod** [comment]
Thanks a lot - works like a charm. For anyone stopping by, sometime in the future: 
**usr/local/bin/mackup backup -f** (Application path can be found via terminal: **which application-name**
