### ISSUE TITLE
Password/Scripts after sleep on wakeup?

### ISSUE THREAD

**Issue by Rmafive** [dustinrue/ControlPlane#439]
I was able to correct the issue with the screensaver password using some suggestions from stack exchange and the official thread on the issue here.  I'm setting my contexts based on my home wifi network, to require a password when I have departed.  However, whenever I wake the computer, the wifi activates slower than the password screen showing on my Macbook Pro.  I can see the script getting executed 1-2 seconds after the password screen shows, but it is too late by then.  Is there any known workaround for this issue?

**Comment by dustinrue** [comment]
I don't believe there is a way to guarantee the timing is correct. If you are trying to set that a password is not required on the screen saver when arriving home, it'll never work because the screen is locked the moment it comes out of stand by.
