### ISSUE TITLE
Know when there is outbound mail stuck in Apple Mail, suspend VPN, configure MacProxy

### ISSUE THREAD

**Issue by mrjcleaver** [dustinrue/ControlPlane#440]
Some of my clients require I use their VPN when working for them. The problem is they have firewalls that prevent SMTP connections.

So I respond to emails. And then sometime later I realize the email got stuck.

I have two strategies:
- Start Mac Proxy to tunnel via SSH; if that doesn't work
- Suspend the client's VPN 

I'd like this to be automatic.

So I need:
- a way to know that email has been stuck for a period of time
- a way to trigger MacProxy
- a way to suspend a VPN connection

Are any of these doable?

Thanks, Martin

**Comment by wedi** [comment]
In your case I would just add a static route.

See e.g. https://support.hidemyass.com/hc/en-us/articles/202720646-How-to-let-websites-and-IPs-bypass-the-VPN-using-static-routing how to do it.

Alternatively you could write a shell script that checks if the SMTP connection is available
if not:
  * set up your proxy via script
  * `scutil —nc start|stop "<YOUR VPN NAME>"`

**Comment by mrjcleaver** [comment]
Thanks Dirk!
