### ISSUE TITLE
1.6.2 crashing and complaining about sparkle framework

### ISSUE THREAD

**Issue by chris78664** [dustinrue/ControlPlane#442]
Tried to install 1.6.2 from Macupdate and it crashing on the 3 machines I tried.  It is complaining about sparkle framework.  Went back to 1.6.1 works fine again.

Thanks,

Chris

**Comment by dustinrue** [comment]
I fixed the issue yesterday so you can try the download again.

**Comment by chris78664** [comment]
Dustin,

Thanks yes the update did fix the initial issue with 1.6.2 from macupdate.

Thanks Again,

Chris
