### ISSUE TITLE
Update dialog grabs input focus

### ISSUE THREAD

**Issue by mryan1539** [dustinrue/ControlPlane#444]
The update dialog grabs input focus, and has twice in the past several days
come up as I was typing something, causing the dialog to receive a return
and proceed to update without me being able to review the notice.

Can we please either make the update dialog not grab input focus, or at least
make it so that there are no default buttons, so you actually have to click on
a button to proceed?

**Comment by dustinrue** [comment]
It’s a sparkle thing so I’m not sure I can do that. I’ll look into it.

**Comment by dustinrue** [comment]
The updater doesn't provide any way for me to modify how it works, there isn't anything I can do at this time.
