### ISSUE TITLE
Sparkle Auto Updater has a vulnerability

### ISSUE THREAD

**Issue by abc2mit** [dustinrue/ControlPlane#450]
The current implementation of Sparkle has a vulnerability that got flagged by my company's scanning software. It's now blocked and I can't use or promote ControlPlane within the company. Can we update Sparkle to the latest version?

**Comment by abc2mit** [comment]
https://sparkle-project.org/documentation/security/

**Comment by dustinrue** [comment]
You can download the latest version at http://controlplaneapp.com/download/1.6.4 which has the updated Sparkle client.

**Comment by abc2mit** [comment]
perfect. thank you!
