### ISSUE TITLE
Laptop lid rule evaluation

### ISSUE THREAD

**Issue by YujiShen** [dustinrue/ControlPlane#451]
When combined with other rules, laptop lid rule will not be evaluated unless its confidence is greater than threshold (Or maybe only laptop lid rule is evaluated, but other rules stop working). This make it useless if I want to use it to trigger a context.

For example, I combined bluetooth (50%) and power source (50%) rules with lid (50%) rule, only bluetooth rule and power source rules will not trigger context change (80%). If it works normally, when I close the lid, the context should change, but it does not.

**Comment by dustinrue** [comment]
I can't replicate this. I've configured a 50% power source rule, 50% lid rule and a 50% wifi rule and I'm able to trigger my test context at 80% confidence.
