### ISSUE TITLE
Context not changing despite rule being active

### ISSUE THREAD

**Issue by eduvik** [dustinrue/ControlPlane#454]
I've set up a couple of rules, and when the rule is triggered, a tick appears in the rule pane showing it's been registered. However, the context associated with the rule does not become activated, and the actions are not triggered. 

I can force the context successfully and the rules get run, and the departure actions get run successfully when I untrigger the rule.

I'm using version 1.6.4 on OSX 10.11.6 (El Capitan)

**Comment by dustinrue** [comment]
When a rule matches it needs to provide enough (more) confidence than is required for a context to become active. Make sure the rule satisfies the confidence needs of the context.

**Comment by eduvik** [comment]
Working now; I changed the 'confidence required to switch' on the General tab of the settings. Interestingly, two different monitors showed different confidence levels.
