### ISSUE TITLE
forced context forgotten after sleep

### ISSUE THREAD

**Issue by schmurfy** [dustinrue/ControlPlane#458]
If I force a context then check "stick forced context" I was hoping that the automatic switching was disabled but it appears that is not the case, if I put the screen to sleep when I log back in it will switch to whatever should be the correct context ignoring what I forced.

is that a bug or is it intended and stick context is not what I am looking for ?

My scenario is that I have a work and home location but I sometime works at home, the work context start my work apps and the home context close them.

PS: I love this app :)

**Comment by dustinrue** [comment]
Automatic switch is always enabled unless you explicitly disable it. I'll look into creating an action that can enable/disable automatic switching in ControlPlane

**Comment by schmurfy** [comment]
What does "stick forced context" means/do then ?
