### ISSUE TITLE
Mount actions always result in prompt in OSX 10.12

### ISSUE THREAD

**Issue by JohnnyricoMC** [dustinrue/ControlPlane#470]
As of OS X 10.12, the mount actions will always result in a prompt for a username and password, regardless of the password for the volume being stored in the keychain:

<img width="506" alt="screenshot 2016-11-05 00 57 53" src="https://cloud.githubusercontent.com/assets/1798635/20026150/f54191c4-a2f6-11e6-88f7-8972cbe8629b.png">

The cause of this appears to lie outside of ControlPlane: Apple no longer permits mounting in /Volumes unless root (their words). Ref: [rdar://27812516: Changes to /Volumes permissions prevent use of mount command](https://openradar.appspot.com/radar?id=4948585099558912)

People in this Apple Developer forum thread have devised a workaround:
[macOS Sierra Automount on Startup | Apple Developer Forums](https://forums.developer.apple.com/thread/51045)
By mounting their network volumes in a different location, e.g. ~/servername/sharename, they are no longer greeted by a password prompt. ControlPlane users could mimic this by employing the ShellScript action (and pointing to a script containing their mount commands) instead of the Mount action.

However, the security problem I see with the various proposed script solutions is they all appear to involve including the password in plain text rather than depending on the keychain.

Is there a way ControlPlane could mount network volumes in a location other than /Volumes while still making use of the Keychain?

**Comment by dustinrue** [comment]
There is nothing I can do to resolve this right now. I get the same behavior even if I manually access shares and I'm assuming it is either now desired behavior of macOS Sierra or a bug.
