### ISSUE TITLE
Feature request: allow applescript to switch to subcontext

### ISSUE THREAD

**Issue by myers** [dustinrue/ControlPlane#471]
https://github.com/dustinrue/ControlPlane/wiki/Controlling-ControlPlane-using-AppleScript outlines how you can use applescript to switch contexts.  Unfortunately this doesn't extend to subcontexts.

If I have a context named `Context`, and a subcontext under that named `Subcontext` then this script should switch to that subcontext.

```
tell application "ControlPlane"
    set current context to "Context/Subcontext"
end tell
```

**Comment by dustinrue** [comment]
Quite likely that sub contexts will go away in favor of just having multiple contexts active. You can use active context evidence source to simulate the old sub context structure if still required.
