### ISSUE TITLE
Bluetooth as evidence source produces lag on Magic Mouse

### ISSUE THREAD

**Issue by moritzp** [dustinrue/ControlPlane#475]
With Bluetooth enabled as evidence source on my MacBook Pro (15" late 2015, MacOS 10.12.1), my Magic Mouse becomes so laggy it's not usable anymore. Having no rule set for bluetooth does not prevent this. If disabling Bluetooth as evidence source, everything is fine.
I'm not sure if other Bluetooth devices are affected.

**Comment by dustinrue** [comment]
What version of ControlPlane do you have. In older versions of ControlPlane it was allowed to scan for bluetooth devices in range which would cause this issue. Newer versions should only know about what is actually connected which avoids the issue.

**Comment by apographon** [comment]
www.apographon.de gibt es leider nicht mehr.
Die eMail wurde an www.shashindo.de weitergeleitet.
