### ISSUE TITLE
controlplane cannot change the password required pref

### ISSUE THREAD

**Issue by garykinetic** [dustinrue/ControlPlane#476]
controlplane cannot change the password required pref for when screensaver comes on or when computer sleeps.

**Comment by tharwan** [comment]
same as https://github.com/dustinrue/ControlPlane/issues/421 I beliefe. Still waiting for this to be fixed too.

**Comment by dustinrue** [comment]
This is an issue that comes up a lot and unfortunately I don't have a good answer for you. Remember that ControlPlane is tapping into undocumented features of OS X to get certain tasks done. As far as I know, there is no other utility out there that can modify the screensaver password setting in the background and for good reason. Apple doesn't want people doing that. 

It's very likely I'll be removing this feature from ControlPlane in the near future.
