### ISSUE TITLE
How much energy/battery power does ControlPlane use?

### ISSUE THREAD

**Issue by sn0wyfall** [dustinrue/ControlPlane#482]
In Activity Monitor, it looks like ControlPlane's average energy impact is about 0.02-0.05, which is extremely low. Is this really its energy impact, or the energy impact for the preferences "app?" Is there any daemon or background process which ControlPlane uses which causes more energy to be needed? Just curious.

**Comment by dustinrue** [comment]
Depends on the number of and what kinds of evidence sources you have enabled. Many of them run on a loop and do work which is why you see the energy impact you do.

**Comment by sn0wyfall** [comment]
I just use one. Maybe that's why the battery usage is low. Too low...
