### ISSUE TITLE
Download link for latest version on https://www.controlplaneapp.com is broken

### ISSUE THREAD

**Issue by c0state** [dustinrue/ControlPlane#483]
The download link on the website, https://www.controlplaneapp.com/download/1.6.4--which looks to be hosted on Dropbox at https://dl.dropboxusercontent.com/u/12850/ControlPlane/ControlPlane-1.6.4.dmg--is currently returning a 404.

**Comment by dustinrue** [comment]
repaired

**Comment by core-code** [comment]
are you sure? i find its impossible to get any working download link from the homepage

**Comment by dustinrue** [comment]
I broke it again when I moved my site over. You can get the most recent version from https://uc7623c46083c7e293e1e735ccb3.dl.dropboxusercontent.com/cd/0/get/AlPevCimNr-vZXgD2_x2Mh7r-YuYblzCbC9lL3zOCypF0DLpyhWuwPeMwMuWXbaMKhSh0xEY99Ba7iV4adZdJc6QEH4OiuoYWowGiBqY23hYxg/file?dl=1

**Comment by core-code** [comment]
thanks for the updated link.

note that the appcast file for auto-updates is also gone now

https://www.controlplaneapp.com/appcast.xml

**Comment by core-code** [comment]
i get Error (403) on that link ;(

**Comment by core-code** [comment]
we are trying to keep 'ControlPlane' in 'Homebrew Cask' over at:

https://github.com/Homebrew/homebrew-cask/pull/66643

is there any working download link for the latest version that we can use?

**Comment by core-code** [comment]
failing any accessible download link, ControlPlane has been removed from Homebrew Cask
