### ISSUE TITLE
high sierra: Insecure Update error

### ISSUE THREAD

**Issue by ssbarnea** [dustinrue/ControlPlane#494]
On High Sierra beta 6 it does popup this window:
![170902-1044](https://user-images.githubusercontent.com/102495/29994919-9276c968-8fd3-11e7-8b41-4587cfe6272c.png)

It seems to be a bug in the update checking.

**Comment by microbug** [comment]
I'm not getting this error on macOS 10.13.1 (on the latest stable public build). Can you confirm if this is still happening for you, and if so how to reproduce it?
