### ISSUE TITLE
Certificate expired (letsencrypt script probably broken)

### ISSUE THREAD

**Issue by WoLpH** [dustinrue/ControlPlane#499]
Just a heads up, the website certificate has expired: https://www.controlplaneapp.com/

**Comment by karbassi** [comment]
Valid as of 2018-06-20. https://www.ssllabs.com/ssltest/analyze.html?d=www.controlplaneapp.com&latest

@dustinrue you can close this.

**Comment by WoLpH** [comment]
yes, works now
